default: &default
  username: postgres
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  username: develop
  database: mic_test_development
test:
  adapter: postgresql
  database: mic_test_test
  pool: 5
  timeout: 5000

staging:
  <<: *default
  username: lider
  database: mic_test_staging

production:
  <<: *default
  username: lider
  database: mic_test_production
